version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test23Project
  gitServerName: githubacc
  gitUrl: https://github.com/Lakshitha-Ramesh-IBM
  gitUsername: Lakshitha-Ramesh-IBM
  gitBranch: main
services:
- serviceName: project.test23.integrations:date
  packages:
  - name: Test23Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.7
